# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

# map paths
map_path: './example_map'
map_ext: '.png'

# starting pose for ego
ego_sx: 0.7
ego_sy: 0.0
ego_stheta: 1.37079632679

# Start pose for opponent (ahead of ego)
opp_sx: 0.7
opp_sy: 1.0
opp_stheta: 1.37079632679 


# raceline path and indices
wpt_path: './example_waypoints.csv' # csv file
wpt_delim: ';' # csv delimiter
wpt_rowskip: 3 # skip first 3 rows
wpt_xind: 1 # x index in csv
wpt_yind: 2 # y index in csv
wpt_thind: 3 # theta index in csv
wpt_vind: 5 # velocity index in csv

# varied params bound
# physical params TODO: understand why there is a max an min??
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147 
lf_max: 0.170 
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345
